services:
  # Combined Service (FastAPI and Streamlit)
  - type: web
    name: tailortalk
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    ports:
      - port: 8501
        name: frontend
      - port: 8000
        name: backend
