services:
  # Backend Service (FastAPI)
  - type: web
    name: calendo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: CALENDAR_ID
        sync: false
    port: 8000

  # Frontend Service (Streamlit)
  - type: web
    name: calendo-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: https://calendo-backend.onrender.com
    port: 8501
